config/routes.rb
MapsExample::Application.routes.draw do

  root "flats#index"
  resources :flats

end

app/models/flat.rb
class Flat < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  # GET /flats
  # GET /flats.json
  def index
    @flats = Flat.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@flats) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
      marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  # GET /flats/1
  # GET /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats
  # POST /flats.json
  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to flats_path, notice: 'Flat was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /flats/1
  # PATCH/PUT /flats/1.json
  def update
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Flat was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /flats/1
  # DELETE /flats/1.json
  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to flats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flat_params
      params.require(:flat).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="row-fluid">
  <div class="col-md-4 col-md-offset-4">
    <div class="row">

      <h1>Create/Edit your flat</h1>

      <%= form_for(@flat) do |f| %>
        <% if @flat.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@flat.errors.count, "error") %> prohibited this flat from being saved:</h2>

            <ul>
            <% @flat.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :address %>
          <%= f.text_field :address, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit "GO", class: "btn btn-primary" %>
        </div>
      <% end %>


    </div>
  </div>

</div>

app/views/flats/_map_box.html.erb
<div class="map_box">
  <h3><%= flat.name %></h3>
  <p><%= flat.address %></p>
  <%= link_to "Details", flat_path(flat), target: :blank, class: "btn btn-warning" %>
</div>

app/views/flats/edit.html.erb
<h1>Editing flat</h1>

<%= render 'form' %>

<%= link_to 'Show', @flat %> |
<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
<div class="row-fluid">
  <div class="col-md-6">
    <div id="map" style='width: 100%; height: 600px;'></div>
  </div>
  <div class="col-md-6">
    <%= link_to new_flat_path do %>
      <button class="btn btn-primary">Add a new flat</button>
    <% end %>

    <hr>

    <% @flats.each do |flat| %>
      <div class="row-fluid">
        <h2><%= link_to flat.name, flat %></h2>
        <p><%= flat.address %></p>
        <%= link_to "Edit", edit_flat_path(flat), class: "btn btn-default" %>
        or
        <%= link_to "delete", flat, method: :delete, data: { confirm: 'Are you sure?' }  %>
      </div>
    <% end %>
  </div>
</div>

<% content_for(:after_js) do %>
  <script type="text/javascript">
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map' } }, function(){
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });
  </script>
<% end %>

app/views/flats/new.html.erb
<%= render 'form' %>

app/views/flats/show.html.erb
<div class="row-fluid">
  <div class="col-md-8 col-md-offset-2">
    <div class="row">
      <h2><%= @flat.name %></h2>
      <p><%= @flat.address %></p>
      <p>Latitude: <%= @flat.latitude %></p>
      <p>Longitude: <%= @flat.longitude %></p>

      <%= link_to "Edit", edit_flat_path(@flat), class: "btn btn-primary" %>
      or
      <%= link_to "get batck to list", flats_path %>
    </div>

    <hr>

    <div class="row">
      <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{@flat.latitude},#{@flat.longitude}&zoom=14&size=640x400&markers=color:black%7C#{@flat.latitude},#{@flat.longitude}" %>
    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dynamic Google Maps</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid">
    <%= yield %>
  </div>

  <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=AIzaSyDANjx3bosEtIyzJaoWs50Wnt6nt_1rmxU" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

  <%= javascript_include_tag "application" %>

  <%= yield(:after_js) %>
</body>
</html>